# Generated by Django 5.1.2 on 2024-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_product_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
